#!/usr/bin/perl

=begin

Generate an initialization file using the specified auth file
and stated requirements.

The resulting file can be run as a user-data script or manually.

=cut

use strict;

my $auth = slurp(shift @ARGV);
my $template = slurp('ec2-initialize.txt');
my $package = slurp('requirements.txt');

$template =~ s/%AUTH%/$auth/;
$template =~ s/%PACKAGES%/$package/;

print $template;

sub slurp {
    my $f = shift;
    local $/;
    open(F, $f) or die "cannot open $f. $!\n";
    <F>
}
