#!/bin/sh

# Fetch and process new comments for all currently open proceedings.
# This script can be run under cron once a day.

export RAILS_ENV=production
dir=$(dirname $0)


# import new proceedings and links to their associated documents
python $dir/proceeding.py run

# queue up documents, if any, for extraction
sh run-task $dir/auth/production/injector.key inject
sh run-task $dir/auth/production/worker.key extract_batch
sh run-task $dir/auth/production/collector.key collect_batch
